[tool]
[tool.flakehell]
base = "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml"
format = "grouped"
max_line_length = 120
show_source = false
exclude = [".ipynb_checkpoints", "setup.py"]

[tool.flakehell.plugins]
pyflakes = ["-F405"]
pycodestyle = ["-W503", "-E722", "-E999"]

[tool.flit]
[tool.flit.scripts]
dgaf = "dgaf.__main__:main"

[tool.flit.metadata.requires-extra]
nox = ["doit", "GitPython", "depfinder", "aiofiles", "appdirs", "typer", "nox", "pathspec", "requests-cache", "tomlkit",]
