[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "dgaf"
author = "deathbeds"
author-email = "tony.fast@gmail.com"
home-page = "http://github.com/deathbeds/dgaf"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = ["doit", "gitpython", "flit", "anyconfig", "python-dotenv"]

[tool.flit.metadata.requires-extra]
mamba = ["mamba"]
test = ["pytest", "nbval"]
doc = ["jupyter-book"]

[tool.flit.entrypoints.console_scripts]
dgaf = "dgaf.__main__:main"

[tool.flit.entrypoints."nbconvert.exporters"]
nikola = "dgaf.exporters:Nikola"

[tool.pytest.ini_options]
addopts = """\
-p no:warnings -p no:importnb -pno:pidgy\
-v\
"""
python_files = "*.py"
norecursedirs="sample .ipynb_checkpoints"