[tool.flit.metadata.requires-extra]
mamba = [ "mamba",]
conda = ["grayskull"]
test = [ "pytest", "nbval", "pytest-click",]
doc = [ "jupyter-book"]

[tool.flit.entrypoints.console_scripts]
dgaf = "dgaf:main"

[tool.flit.entrypoints."nbconvert.exporters"]
nikola = "dgaf.exporters:Nikola"
