[tool]
[tool.pytest]
[tool.pytest.ini_options]
addopts = "-s"
minversion = 6.2
norecursedirs = "*.egg-info .eggs .gitignore .ipynb_checkpoints .nox .pytest_cache .vscode __pycache__ dist"

[tool.flakehell]
base = "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml"
exclude = [".ipynb_checkpoints", "setup.py"]
format = "grouped"
max_line_length = 120
show_source = false

[tool.flakehell.plugins]
pycodestyle = ["-W503", "-E722", "-E999"]
pyflakes = ["-F405"]

[tool.flit]
[tool.flit.scripts]
dgaf = "dgaf.__main__:main"

[tool.flit.metadata.requires-extra]
core = [
  "doit",
  "GitPython",
  "pathspec",
]
extras = [
  "depfinder",
  "aiofiles",
  "appdirs",
  "typer",
  "json-e",
  "flit",
  "poetry",
  "requests-cache",
  "tomlkit",
  "nox",
]
