[tool]
[tool.pytest]
[tool.pytest.ini_options]
addopts = "-s"
norecursedirs = "*.egg-info .eggs .gitignore .ipynb_checkpoints .nox .pytest_cache .vscode __pycache__ dist"
minversion = 6.2

[tool.flakehell]
base = "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml"
format = "grouped"
max_line_length = 120
show_source = false
exclude = [".ipynb_checkpoints", "setup.py"]

[tool.flakehell.plugins]
pyflakes = ["-F405"]
pycodestyle = ["-W503", "-E722", "-E999"]

[tool.flit]
[tool.flit.scripts]
dgaf = "dgaf.__main__:main"

[tool.flit.metadata.requires-extra]
configure = [
    "doit", "GitPython", "depfinder", 
    "aiofiles", "appdirs", "typer", 
    "json-e", "pathspec", "flit", "poetry",
    "requests-cache", "tomlkit", "nox"]

